version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
    groups:
      actions-dependencies:
        update-types:
        - "minor"
        - "patch"
        - "major"
        patterns:
          - "*"

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
    groups:
      dev-dependencies:
        update-types:
        - "minor"
        - "patch"
        - "major"
        patterns:
          - "*"

  - package-ecosystem: gradle
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
    groups:
      maven-dependencies:
        update-types:
        - "minor"
        - "patch"
        - "major"
        patterns:
          - "*"
